<template>
  <md-tabs md-sync-route>
    <md-tab
      id="parcels"
      md-label="Percelen"
      to="/farm/parcels/"
    />
    <md-tab
      id="measures"
      md-label="Maatregelen"
      to="/farm/measures/"
    />
    <md-tab
      id="output"
      md-label="Nutriënten"
      to="/farm/nutrients/"
    />
  </md-tabs>
</template>
